version: '3'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

    volumes:
      - staticfiles:/app/staticfiles
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - staticfiles:/staticfiles
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  staticfiles:
  frontend:
  pgdbdata:
